/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SituacaoRouteImport } from './routes/situacao'
import { Route as RevisaoSemanalRouteImport } from './routes/revisao-semanal'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'
import { Route as GasolinaRouteImport } from './routes/gasolina'
import { Route as FinancialStateRouteImport } from './routes/financial-state'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacaoRoute = SituacaoRouteImport.update({
  id: '/situacao',
  path: '/situacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoSemanalRoute = RevisaoSemanalRouteImport.update({
  id: '/revisao-semanal',
  path: '/revisao-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrentesRoute = RecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const GasolinaRoute = GasolinaRouteImport.update({
  id: '/gasolina',
  path: '/gasolina',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialStateRoute = FinancialStateRouteImport.update({
  id: '/financial-state',
  path: '/financial-state',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/recorrentes': typeof RecorrentesRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/recorrentes': typeof RecorrentesRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof BudgetsRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/recorrentes': typeof RecorrentesRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budgets'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contas-a-pagar'
    | '/crisis'
    | '/dashboard'
    | '/estoque'
    | '/financial-state'
    | '/gasolina'
    | '/recorrentes'
    | '/revisao-semanal'
    | '/situacao'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budgets'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contas-a-pagar'
    | '/crisis'
    | '/dashboard'
    | '/estoque'
    | '/financial-state'
    | '/gasolina'
    | '/recorrentes'
    | '/revisao-semanal'
    | '/situacao'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/budgets'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contas-a-pagar'
    | '/crisis'
    | '/dashboard'
    | '/estoque'
    | '/financial-state'
    | '/gasolina'
    | '/recorrentes'
    | '/revisao-semanal'
    | '/situacao'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BudgetsRoute: typeof BudgetsRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  CrisisRoute: typeof CrisisRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FinancialStateRoute: typeof FinancialStateRoute
  GasolinaRoute: typeof GasolinaRoute
  RecorrentesRoute: typeof RecorrentesRoute
  RevisaoSemanalRoute: typeof RevisaoSemanalRoute
  SituacaoRoute: typeof SituacaoRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situacao': {
      id: '/situacao'
      path: '/situacao'
      fullPath: '/situacao'
      preLoaderRoute: typeof SituacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao-semanal': {
      id: '/revisao-semanal'
      path: '/revisao-semanal'
      fullPath: '/revisao-semanal'
      preLoaderRoute: typeof RevisaoSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrentes': {
      id: '/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof RecorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gasolina': {
      id: '/gasolina'
      path: '/gasolina'
      fullPath: '/gasolina'
      preLoaderRoute: typeof GasolinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-state': {
      id: '/financial-state'
      path: '/financial-state'
      fullPath: '/financial-state'
      preLoaderRoute: typeof FinancialStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BudgetsRoute: BudgetsRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  CrisisRoute: CrisisRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FinancialStateRoute: FinancialStateRoute,
  GasolinaRoute: GasolinaRoute,
  RecorrentesRoute: RecorrentesRoute,
  RevisaoSemanalRoute: RevisaoSemanalRoute,
  SituacaoRoute: SituacaoRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
