/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DreRouteImport } from './routes/dre'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SituacaoRouteImport } from './routes/situacao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RevisaoSemanalRouteImport } from './routes/revisao-semanal'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as GasolinaRouteImport } from './routes/gasolina'
import { Route as FinancialStateRouteImport } from './routes/financial-state'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstoqueRevisaoSemanalRouteImport } from './routes/estoque.revisao-semanal'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'

const DreRoute = DreRouteImport.update({ id: '/dre', path: '/dre', getParentRoute: () => rootRouteImport } as any)
const TransactionsRoute = TransactionsRouteImport.update({ id: '/transactions', path: '/transactions', getParentRoute: () => rootRouteImport } as any)
const SituacaoRoute = SituacaoRouteImport.update({ id: '/situacao', path: '/situacao', getParentRoute: () => rootRouteImport } as any)
const RelatoriosRoute = RelatoriosRouteImport.update({ id: '/relatorios', path: '/relatorios', getParentRoute: () => rootRouteImport } as any)
const RevisaoSemanalRoute = RevisaoSemanalRouteImport.update({ id: '/revisao-semanal', path: '/revisao-semanal', getParentRoute: () => rootRouteImport } as any)
const RecorrentesRoute = RecorrentesRouteImport.update({ id: '/recorrentes', path: '/recorrentes', getParentRoute: () => rootRouteImport } as any)
const MembrosRoute = MembrosRouteImport.update({ id: '/membros', path: '/membros', getParentRoute: () => rootRouteImport } as any)
const ManutencaoRoute = ManutencaoRouteImport.update({ id: '/manutencao', path: '/manutencao', getParentRoute: () => rootRouteImport } as any)
const GasolinaRoute = GasolinaRouteImport.update({ id: '/gasolina', path: '/gasolina', getParentRoute: () => rootRouteImport } as any)
const FinancialStateRoute = FinancialStateRouteImport.update({ id: '/financial-state', path: '/financial-state', getParentRoute: () => rootRouteImport } as any)
const EstoqueRoute = EstoqueRouteImport.update({ id: '/estoque', path: '/estoque', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const CrisisRoute = CrisisRouteImport.update({ id: '/crisis', path: '/crisis', getParentRoute: () => rootRouteImport } as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({ id: '/contas-a-pagar', path: '/contas-a-pagar', getParentRoute: () => rootRouteImport } as any)
const ContasRoute = ContasRouteImport.update({ id: '/contas', path: '/contas', getParentRoute: () => rootRouteImport } as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => rootRouteImport } as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({ id: '/conciliacao', path: '/conciliacao', getParentRoute: () => rootRouteImport } as any)
const ComprasRoute = ComprasRouteImport.update({ id: '/compras', path: '/compras', getParentRoute: () => rootRouteImport } as any)
const BudgetsRoute = BudgetsRouteImport.update({ id: '/budgets', path: '/budgets', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AssistenteRoute = AssistenteRouteImport.update({ id: '/assistente', path: '/assistente', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const EstoqueRevisaoSemanalRoute = EstoqueRevisaoSemanalRouteImport.update({ id: '/estoque/revisao-semanal', path: '/revisao-semanal', getParentRoute: () => EstoqueRoute } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({ id: '/auth/reset-password', path: '/reset-password', getParentRoute: () => AuthRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/budgets': typeof BudgetsRoute
  '/compras': typeof ComprasRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/manutencao': typeof ManutencaoRoute
  '/membros': typeof MembrosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/dre': typeof DreRoute
  '/transactions': typeof TransactionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/estoque/revisao-semanal': typeof EstoqueRevisaoSemanalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/budgets': typeof BudgetsRoute
  '/compras': typeof ComprasRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/manutencao': typeof ManutencaoRoute
  '/membros': typeof MembrosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/dre': typeof DreRoute
  '/transactions': typeof TransactionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/estoque/revisao-semanal': typeof EstoqueRevisaoSemanalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/budgets': typeof BudgetsRoute
  '/compras': typeof ComprasRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/crisis': typeof CrisisRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financial-state': typeof FinancialStateRoute
  '/gasolina': typeof GasolinaRoute
  '/manutencao': typeof ManutencaoRoute
  '/membros': typeof MembrosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao-semanal': typeof RevisaoSemanalRoute
  '/situacao': typeof SituacaoRoute
  '/dre': typeof DreRoute
  '/transactions': typeof TransactionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/estoque/revisao-semanal': typeof EstoqueRevisaoSemanalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistente' | '/auth' | '/budgets' | '/compras' | '/conciliacao' | '/configuracoes' | '/contas' | '/contas-a-pagar' | '/crisis' | '/dashboard' | '/estoque' | '/financial-state' | '/gasolina' | '/manutencao' | '/membros' | '/recorrentes' | '/relatorios' | '/revisao-semanal' | '/situacao' | '/transactions' | '/auth/reset-password' | '/estoque/revisao-semanal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistente' | '/auth' | '/budgets' | '/compras' | '/conciliacao' | '/configuracoes' | '/contas' | '/contas-a-pagar' | '/crisis' | '/dashboard' | '/estoque' | '/financial-state' | '/gasolina' | '/manutencao' | '/membros' | '/recorrentes' | '/relatorios' | '/revisao-semanal' | '/situacao' | '/transactions' | '/auth/reset-password' | '/estoque/revisao-semanal'
  id: '__root__' | '/' | '/assistente' | '/auth' | '/budgets' | '/compras' | '/conciliacao' | '/configuracoes' | '/contas' | '/contas-a-pagar' | '/crisis' | '/dashboard' | '/estoque' | '/financial-state' | '/gasolina' | '/manutencao' | '/membros' | '/recorrentes' | '/relatorios' | '/revisao-semanal' | '/situacao' | '/transactions' | '/auth/reset-password' | '/estoque/revisao-semanal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRouteWithChildren
  BudgetsRoute: typeof BudgetsRoute
  ComprasRoute: typeof ComprasRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  CrisisRoute: typeof CrisisRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  FinancialStateRoute: typeof FinancialStateRoute
  GasolinaRoute: typeof GasolinaRoute
  ManutencaoRoute: typeof ManutencaoRoute
  MembrosRoute: typeof MembrosRoute
  RecorrentesRoute: typeof RecorrentesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RevisaoSemanalRoute: typeof RevisaoSemanalRoute
  SituacaoRoute: typeof SituacaoRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': { id: '/relatorios'; path: '/relatorios'; fullPath: '/relatorios'; preLoaderRoute: typeof RelatoriosRouteImport; parentRoute: typeof rootRouteImport }
    '/revisao-semanal': { id: '/revisao-semanal'; path: '/revisao-semanal'; fullPath: '/revisao-semanal'; preLoaderRoute: typeof RevisaoSemanalRouteImport; parentRoute: typeof rootRouteImport }
    '/transactions': { id: '/transactions'; path: '/transactions'; fullPath: '/transactions'; preLoaderRoute: typeof TransactionsRouteImport; parentRoute: typeof rootRouteImport }
    '/situacao': { id: '/situacao'; path: '/situacao'; fullPath: '/situacao'; preLoaderRoute: typeof SituacaoRouteImport; parentRoute: typeof rootRouteImport }
    '/recorrentes': { id: '/recorrentes'; path: '/recorrentes'; fullPath: '/recorrentes'; preLoaderRoute: typeof RecorrentesRouteImport; parentRoute: typeof rootRouteImport }
    '/membros': { id: '/membros'; path: '/membros'; fullPath: '/membros'; preLoaderRoute: typeof MembrosRouteImport; parentRoute: typeof rootRouteImport }
    '/manutencao': { id: '/manutencao'; path: '/manutencao'; fullPath: '/manutencao'; preLoaderRoute: typeof ManutencaoRouteImport; parentRoute: typeof rootRouteImport }
    '/gasolina': { id: '/gasolina'; path: '/gasolina'; fullPath: '/gasolina'; preLoaderRoute: typeof GasolinaRouteImport; parentRoute: typeof rootRouteImport }
    '/financial-state': { id: '/financial-state'; path: '/financial-state'; fullPath: '/financial-state'; preLoaderRoute: typeof FinancialStateRouteImport; parentRoute: typeof rootRouteImport }
    '/estoque': { id: '/estoque'; path: '/estoque'; fullPath: '/estoque'; preLoaderRoute: typeof EstoqueRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/crisis': { id: '/crisis'; path: '/crisis'; fullPath: '/crisis'; preLoaderRoute: typeof CrisisRouteImport; parentRoute: typeof rootRouteImport }
    '/contas-a-pagar': { id: '/contas-a-pagar'; path: '/contas-a-pagar'; fullPath: '/contas-a-pagar'; preLoaderRoute: typeof ContasAPagarRouteImport; parentRoute: typeof rootRouteImport }
    '/contas': { id: '/contas'; path: '/contas'; fullPath: '/contas'; preLoaderRoute: typeof ContasRouteImport; parentRoute: typeof rootRouteImport }
    '/configuracoes': { id: '/configuracoes'; path: '/configuracoes'; fullPath: '/configuracoes'; preLoaderRoute: typeof ConfiguracoesRouteImport; parentRoute: typeof rootRouteImport }
    '/conciliacao': { id: '/conciliacao'; path: '/conciliacao'; fullPath: '/conciliacao'; preLoaderRoute: typeof ConciliacaoRouteImport; parentRoute: typeof rootRouteImport }
    '/compras': { id: '/compras'; path: '/compras'; fullPath: '/compras'; preLoaderRoute: typeof ComprasRouteImport; parentRoute: typeof rootRouteImport }
    '/budgets': { id: '/budgets'; path: '/budgets'; fullPath: '/budgets'; preLoaderRoute: typeof BudgetsRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/assistente': { id: '/assistente'; path: '/assistente'; fullPath: '/assistente'; preLoaderRoute: typeof AssistenteRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/estoque/revisao-semanal': { id: '/estoque/revisao-semanal'; path: '/revisao-semanal'; fullPath: '/estoque/revisao-semanal'; preLoaderRoute: typeof EstoqueRevisaoSemanalRouteImport; parentRoute: typeof EstoqueRoute }
    '/auth/reset-password': { id: '/auth/reset-password'; path: '/reset-password'; fullPath: '/auth/reset-password'; preLoaderRoute: typeof AuthResetPasswordRouteImport; parentRoute: typeof AuthRoute }
  }
}

interface AuthRouteChildren { AuthResetPasswordRoute: typeof AuthResetPasswordRoute }
const AuthRouteChildren: AuthRouteChildren = { AuthResetPasswordRoute: AuthResetPasswordRoute }
const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EstoqueRouteChildren { EstoqueRevisaoSemanalRoute: typeof EstoqueRevisaoSemanalRoute }
const EstoqueRouteChildren: EstoqueRouteChildren = { EstoqueRevisaoSemanalRoute: EstoqueRevisaoSemanalRoute }
const EstoqueRouteWithChildren = EstoqueRoute._addFileChildren(EstoqueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AssistenteRoute, AuthRoute: AuthRouteWithChildren,
  BudgetsRoute, ComprasRoute, ConciliacaoRoute, ConfiguracoesRoute,
  ContasRoute, ContasAPagarRoute, CrisisRoute, DashboardRoute,
  EstoqueRoute: EstoqueRouteWithChildren, FinancialStateRoute,
  GasolinaRoute, ManutencaoRoute, MembrosRoute, RecorrentesRoute,
  RelatoriosRoute, RevisaoSemanalRoute, SituacaoRoute, TransactionsRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
