// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// BANCO PRINCIPAL — não alterar
export const SUPABASE_URL = "https://mmqoyozyeidxbgbxqnda.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_UvQKkzE7smFYlWpeOxnv6A_MEYtwUYX";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
